theme: null
markdown: kramdown

url: "https://kevin109.github.io"
baseurl: ""
title: "TFT & SBC Integration Notes"
description: "Technical notes for TFT display configuration, Rockchip SBC development, Linux LCD debugging, and Android embedded board integration."


plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: custom
